name: 'Terraform CI'
run-name: ${{ github.event.head_commit.message }}

on:
  # Trigger the workflow on pull request to main
  pull_request:
    branches:
      - main
  # Trigger the workflow on push to any branch except main
  push:
    branches:
      - '*'
      - '!main'
  # Trigger the workflow manually
  workflow_dispatch:

env:
  CHECKOV_CONFIG_FILE_PATH: .config/checkov.yaml
  TERRAFORM_DOCS_CONFIG_FILE_PATH: .config/terraform-docs.yaml
  TERRAFORM_VERSION: 1.7.5
  TFLINT_CONFIG_FILE_PATH: .config/tflint.hcl
  TFLINT_URI: https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # Install TFLint
      - name: Install TFLint
        run: curl -s ${{ env.TFLINT_URI }} | bash

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init -backend=false -no-color

      # Format Terraform files
      - name: Terraform Format
        run: terraform fmt -check -no-color

      # Validate Terraform files
      - name: Terraform Validate
        run: terraform validate -no-color

      # Run Terraform unit tests
      - name: Terraform Unit Tests
        run: terraform test -test-directory=tests/unit -no-color

      # Validate Terraform files with TFLint
      - name: TFLint
        run: |
          tflint --init --config=${{ env.TFLINT_CONFIG_FILE_PATH }} --no-color
          if [[ $? -ne 0 ]]; then
            echo "::error::TFLint reported failures"
            exit 1
          fi

      # Validate Terraform documentation with terraform-docs
      - name: Terraform Docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: ${{ env.TERRAFORM_DOCS_CONFIG_FILE_PATH }}
          git-commit-message: 'docs: terraform-docs automated update'
          git-push: 'true'
          output-file: README.md
          output-method: inject
          template: <!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->
          working-dir: .

      # Validate Terraform configuration with Checkov
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          config_file: ${{ env.CHECKOV_CONFIG_FILE_PATH }}
          output_format: cli,sarif
          output_file_path: console,checkov.sarif
